#!/bin/sh

# ******************************************************************* #
# 3-data scripts have filenames that correspond to data names in the  #
# context.  If this node is told it requires data 'xyz' and a script  #
# in the 3-data directory bears the name 'xyz' then it is called.     #
# The data value has already been written out to a temporary file.    #
# The absolute path of that file is given as argument $1 to this      #
# script for you to do as you please.                                 #
# ******************************************************************* #

RELDIR=`dirname $0`
ABSDIR=`cd $RELDIR; pwd`
echo "Hello from \"$ABSDIR/$0\""

echo ""
echo "'gridmap' data"
echo "Filename with data value: $1"

echo "Copying that to /etc/grid-security/grid-mapfile"

cp $1 /etc/grid-security/grid-mapfile


