<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="NimbusContextBroker" targetNamespace="http://www.globus.org/2008/12/nimbus/contextualization/service" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:binding="http://www.globus.org/2008/12/nimbus/contextualization/bindings" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://www.globus.org/2008/12/nimbus/contextualization/bindings" location="nimbus_ctx_bindings.wsdl"/>
  <wsdl:service name="NimbusContextBrokerService">
    <wsdl:port name="NimbusContextBrokerPortTypePort" binding="binding:NimbusContextBrokerPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
