/*
 * Copyright 1999-2008 University of Chicago
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package org.globus.workspace.service.impls.async;

import org.globus.workspace.WorkspaceConstants;
import org.globus.workspace.Lager;
import org.globus.workspace.TempLocator;
import org.globus.workspace.service.binding.vm.VirtualMachine;

public class WorkspaceRequestContext {

    // locator for the timebeing, will move away from this 
    private final TempLocator locator;

    private final Lager lager;

    // required by all requests, but not by validation interface
    private final int id;
    private final String name;

    // may stay invalid
    private int notify = WorkspaceConstants.STATE_INVALID;

    // may be null:
    private VirtualMachine vm;

    // May optionally be set false by task dispatcher. Since only the task
    // implementation knows if it will be touching anything on a RequiredVMM,
    // it has to decide for itself if it should act or not (it's not
    // lovely but allows for flexible command implementations).
    private boolean vmmAccessOK = true;

    // Group ID will be set by task dispatcher if task is part of a group.
    // The group semantics are ultimately dictated by the task set
    // implementation.
    private String groupID;
    private int groupSize;

    // Will be set only if this is part of a request generated by a group
    // operation.
    // Not overloading groupID field null-ness to mean not part of a group
    // request, task implementation may want knowledge of the group ID even
    // if this task is not part of a group request.
    private boolean isPartOfGroupRequest;

    // Will be set true by task dispatcher if this is the last request of a
    // group request (this is somewhat of a hack).
    // It may be taken advantage of by certain backends, it is ultimately up
    // to the task set implementation if it wants to wait for this before
    // doing certain things in aggregate or to just ignore it.
    // Always will be false if isPartOfGroupRequest is false.
    private boolean isLastInGroup;

    public WorkspaceRequestContext(int id,
                                   String name,
                                   TempLocator aLocator,
                                   Lager lagerImpl) {

        this.id = id;
        this.name = name;

        if (aLocator == null) {
            throw new IllegalArgumentException("aLocator may not be null");
        }
        this.locator = aLocator;

        if (lagerImpl == null) {
            throw new IllegalArgumentException("lagerImpl may not be null");
        }
        this.lager = lagerImpl;
    }

    public boolean equals(Object obj) {
        return obj instanceof WorkspaceRequestContext &&
                obj.hashCode() == this.hashCode();
    }

    public int hashCode() {
        int result = 42;
        result += this.id;
        result += this.name.hashCode();
        if (this.vm != null) {
            result += this.vm.hashCode();
        }
        return result + this.notify;
    }

    public int getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public TempLocator getLocator() {
        return this.locator;
    }

    public Lager lager() {
        return this.lager;
    }

    public VirtualMachine getVm() {
        return this.vm;
    }

    public void setVm(VirtualMachine vm) {
        this.vm = vm;
    }

    public int getNotify() {
        return this.notify;
    }

    public void setNotify(int notify) {
        this.notify = notify;
    }

    public boolean isVmmAccessOK() {
        return this.vmmAccessOK;
    }

    public void setVmmAccessOK(boolean vmmAccessOK) {
        this.vmmAccessOK = vmmAccessOK;
    }

    public String getGroupID() {
        return this.groupID;
    }

    public void setGroupID(String groupID) {
        this.groupID = groupID;
    }

    public int getGroupSize() {
        return this.groupSize;
    }

    public void setGroupSize(int groupSize) {
        this.groupSize = groupSize;
    }

    public boolean isPartOfGroupRequest() {
        return this.isPartOfGroupRequest;
    }

    public void setPartOfGroupRequest(boolean partOfGroupRequest) {
        this.isPartOfGroupRequest = partOfGroupRequest;
    }

    public boolean isLastInGroup() {
        return this.isLastInGroup;
    }

    public void setLastInGroup(boolean lastInGroup) {
        this.isLastInGroup = lastInGroup;
    }
}
